sdf: ../../sdfs/1guilla/1guilla.sdf
spawn:
  loader: 0
  mode: !!python/object/apply:farms_core.model.options.SpawnMode
  - transverse
  pose:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 3.141592653589793
  velocity:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  extras: {}
morphology:
  links:
  - name: link0
    collisions: true
    friction:
    - 0.2
    - 0
    - 0
    extras:
      restitution: 0.5
      linearDamping: 0
      angularDamping: 0
    fluid_interaction: true
    density: 800.0
  - name: link1
    collisions: true
    friction:
    - 0.2
    - 0
    - 0
    extras:
      restitution: 0.5
      linearDamping: 0
      angularDamping: 0
    fluid_interaction: true
    density: 800.0
  - name: link2
    collisions: true
    friction:
    - 0.2
    - 0
    - 0
    extras:
      restitution: 0.5
      linearDamping: 0
      angularDamping: 0
    fluid_interaction: true
    density: 800.0
  - name: link3
    collisions: true
    friction:
    - 0.2
    - 0
    - 0
    extras:
      restitution: 0.5
      linearDamping: 0
      angularDamping: 0
    fluid_interaction: true
    density: 800.0
  - name: link4
    collisions: true
    friction:
    - 0.2
    - 0
    - 0
    extras:
      restitution: 0.5
      linearDamping: 0
      angularDamping: 0
    fluid_interaction: true
    density: 800.0
  - name: link5
    collisions: true
    friction:
    - 0.2
    - 0
    - 0
    extras:
      restitution: 0.5
      linearDamping: 0
      angularDamping: 0
    fluid_interaction: true
    density: 800.0
  - name: link6
    collisions: true
    friction:
    - 0.2
    - 0
    - 0
    extras:
      restitution: 0.5
      linearDamping: 0
      angularDamping: 0
    fluid_interaction: true
    density: 800.0
  - name: link7
    collisions: true
    friction:
    - 0.2
    - 0
    - 0
    extras:
      restitution: 0.5
      linearDamping: 0
      angularDamping: 0
    fluid_interaction: true
    density: 800.0
  - name: link8
    collisions: true
    friction:
    - 0.2
    - 0
    - 0
    extras:
      restitution: 0.5
      linearDamping: 0
      angularDamping: 0
    fluid_interaction: true
    density: 800.0
  self_collisions: []
  joints:
  - name: joint_body_00
    initial:
    - 0
    - 0
    limits:
    - - -.inf
      - .inf
    - - -.inf
      - .inf
    stiffness: 0
    springref: 0
    damping: 0
    extras: {}
  - name: joint_body_01
    initial:
    - 0
    - 0
    limits:
    - - -.inf
      - .inf
    - - -.inf
      - .inf
    stiffness: 0
    springref: 0
    damping: 0
    extras: {}
  - name: joint_body_02
    initial:
    - 0
    - 0
    limits:
    - - -.inf
      - .inf
    - - -.inf
      - .inf
    stiffness: 0
    springref: 0
    damping: 0
    extras: {}
  - name: joint_body_03
    initial:
    - 0
    - 0
    limits:
    - - -.inf
      - .inf
    - - -.inf
      - .inf
    stiffness: 0
    springref: 0
    damping: 0
    extras: {}
  - name: joint_body_04
    initial:
    - 0
    - 0
    limits:
    - - -.inf
      - .inf
    - - -.inf
      - .inf
    stiffness: 0
    springref: 0
    damping: 0
    extras: {}
  - name: joint_body_05
    initial:
    - 0
    - 0
    limits:
    - - -.inf
      - .inf
    - - -.inf
      - .inf
    stiffness: 0
    springref: 0
    damping: 0
    extras: {}
  - name: joint_body_06
    initial:
    - 0
    - 0
    limits:
    - - -.inf
      - .inf
    - - -.inf
      - .inf
    stiffness: 0
    springref: 0
    damping: 0
    extras: {}
  - name: joint_body_07
    initial:
    - 0
    - 0
    limits:
    - - -.inf
      - .inf
    - - -.inf
      - .inf
    stiffness: 0
    springref: 0
    damping: 0
    extras: {}
control:
  sensors:
    links:
    - link0
    - link1
    - link2
    - link3
    - link4
    - link5
    - link6
    - link7
    - link8
    joints:
    - joint_body_00
    - joint_body_01
    - joint_body_02
    - joint_body_03
    - joint_body_04
    - joint_body_05
    - joint_body_06
    - joint_body_07
    contacts: []
    xfrc:
    - link0
    - link1
    - link2
    - link3
    - link4
    - link5
    - link6
    - link7
    - link8
    muscles: []
    adhesions: []
    visuals: []
  motors:
    - joint_name: joint_body_00
      control_types:
      - position
      limits_torque:
      - -.inf
      - .inf
      gains:
      - 50.0
      - 5.0
      - 0
    - joint_name: joint_body_01
      control_types:
      - position
      limits_torque:
      - -.inf
      - .inf
      gains:
      - 50.0
      - 5.0
      - 0
    - joint_name: joint_body_02
      control_types:
      - position
      limits_torque:
      - -.inf
      - .inf
      gains:
      - 50.0
      - 5.0
      - 0
    - joint_name: joint_body_03
      control_types:
      - position
      limits_torque:
      - -.inf
      - .inf
      gains:
      - 50.0
      - 5.0
      - 0
    - joint_name: joint_body_04
      control_types:
      - position
      limits_torque:
      - -.inf
      - .inf
      gains:
      - 50.0
      - 5.0
      - 0
    - joint_name: joint_body_05
      control_types:
      - position
      limits_torque:
      - -.inf
      - .inf
      gains:
      - 50.0
      - 5.0
      - 0
    - joint_name: joint_body_06
      control_types:
      - position
      limits_torque:
      - -.inf
      - .inf
      gains:
      - 50.0
      - 5.0
      - 0
    - joint_name: joint_body_07
      control_types:
      - position
      limits_torque:
      - -.inf
      - .inf
      gains:
      - 50.0
      - 5.0
      - 0
extensions:
- loader: lilytorch.farms_examples.1guillasim.1guilla_position_control.controller.PositionController
  config: {}

# - loader: farms_mujoco.swimming.extension.SwimmingExtension
#   config:
#     water_properties: null
