spawn:
  loader: 0
  mode: !!python/object/apply:farms_core.model.options.SpawnMode
  - transverse
  pose:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 3.141592653589793
  velocity:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  extras: {}
sdf: ../../sdfs/zebrafish/zebrafish_v1_triangulated/sdf/zebrafish.sdf
morphology:
  links:
  - name: link_0
    collisions: true
    friction:
    - 0.2
    - 0
    - 0
    extras: {}
    fluid_interaction: true
    density: 1000.0
  - name: link_1
    collisions: true
    friction:
    - 0.2
    - 0
    - 0
    extras: {}
    fluid_interaction: true
    density: 1000.0
  - name: link_2
    collisions: true
    friction:
    - 0.2
    - 0
    - 0
    extras: {}
    fluid_interaction: true
    density: 1000.0
  - name: link_3
    collisions: true
    friction:
    - 0.2
    - 0
    - 0
    extras: {}
    fluid_interaction: true
    density: 1000.0
  - name: link_4
    collisions: true
    friction:
    - 0.2
    - 0
    - 0
    extras: {}
    fluid_interaction: true
    density: 1000.0
  - name: link_5
    collisions: true
    friction:
    - 0.2
    - 0
    - 0
    extras: {}
    fluid_interaction: true
    density: 1000.0
  - name: link_6
    collisions: true
    friction:
    - 0.2
    - 0
    - 0
    extras: {}
    fluid_interaction: true
    density: 1000.0
  - name: link_7
    collisions: true
    friction:
    - 0.2
    - 0
    - 0
    extras: {}
    fluid_interaction: true
    density: 1000.0
  - name: link_8
    collisions: true
    friction:
    - 0.2
    - 0
    - 0
    extras: {}
    fluid_interaction: true
    density: 1000.0
  - name: link_9
    collisions: true
    friction:
    - 0.2
    - 0
    - 0
    extras: {}
    fluid_interaction: true
    density: 1000.0
  - name: link_10
    collisions: true
    friction:
    - 0.2
    - 0
    - 0
    extras: {}
    fluid_interaction: true
    density: 1000.0
  - name: link_11
    collisions: true
    friction:
    - 0.2
    - 0
    - 0
    extras: {}
    fluid_interaction: true
    density: 1000.0
  - name: link_12
    collisions: true
    friction:
    - 0.2
    - 0
    - 0
    extras: {}
    fluid_interaction: true
    density: 1000.0
  - name: link_13
    collisions: true
    friction:
    - 0.2
    - 0
    - 0
    extras: {}
    fluid_interaction: true
    density: 1000.0
  - name: link_14
    collisions: true
    friction:
    - 0.2
    - 0
    - 0
    extras: {}
    fluid_interaction: true
    density: 1000.0
  - name: link_15
    collisions: true
    friction:
    - 0.2
    - 0
    - 0
    extras: {}
    fluid_interaction: true
    density: 1000.0
  joints:
  - name: joint_0
    initial:
    - 0
    - 0
    limits:
    - - -.inf
      - .inf
    - - -.inf
      - .inf
    stiffness: 0
    springref: 0
    damping: 0
    extras: {}
  - name: joint_1
    initial:
    - 0
    - 0
    limits:
    - - -.inf
      - .inf
    - - -.inf
      - .inf
    stiffness: 0
    springref: 0
    damping: 0
    extras: {}
  - name: joint_2
    initial:
    - 0
    - 0
    limits:
    - - -.inf
      - .inf
    - - -.inf
      - .inf
    stiffness: 0
    springref: 0
    damping: 0
    extras: {}
  - name: joint_3
    initial:
    - 0
    - 0
    limits:
    - - -.inf
      - .inf
    - - -.inf
      - .inf
    stiffness: 0
    springref: 0
    damping: 0
    extras: {}
  - name: joint_4
    initial:
    - 0
    - 0
    limits:
    - - -.inf
      - .inf
    - - -.inf
      - .inf
    stiffness: 0
    springref: 0
    damping: 0
    extras: {}
  - name: joint_5
    initial:
    - 0
    - 0
    limits:
    - - -.inf
      - .inf
    - - -.inf
      - .inf
    stiffness: 0
    springref: 0
    damping: 0
    extras: {}
  - name: joint_6
    initial:
    - 0
    - 0
    limits:
    - - -.inf
      - .inf
    - - -.inf
      - .inf
    stiffness: 0
    springref: 0
    damping: 0
    extras: {}
  - name: joint_7
    initial:
    - 0
    - 0
    limits:
    - - -.inf
      - .inf
    - - -.inf
      - .inf
    stiffness: 0
    springref: 0
    damping: 0
    extras: {}
  - name: joint_8
    initial:
    - 0
    - 0
    limits:
    - - -.inf
      - .inf
    - - -.inf
      - .inf
    stiffness: 0
    springref: 0
    damping: 0
    extras: {}
  - name: joint_9
    initial:
    - 0
    - 0
    limits:
    - - -.inf
      - .inf
    - - -.inf
      - .inf
    stiffness: 0
    springref: 0
    damping: 0
    extras: {}
  - name: joint_10
    initial:
    - 0
    - 0
    limits:
    - - -.inf
      - .inf
    - - -.inf
      - .inf
    stiffness: 0
    springref: 0
    damping: 0
    extras: {}
  - name: joint_11
    initial:
    - 0
    - 0
    limits:
    - - -.inf
      - .inf
    - - -.inf
      - .inf
    stiffness: 0
    springref: 0
    damping: 0
    extras: {}
  - name: joint_12
    initial:
    - 0
    - 0
    limits:
    - - -.inf
      - .inf
    - - -.inf
      - .inf
    stiffness: 0
    springref: 0
    damping: 0
    extras: {}
  - name: joint_13
    initial:
    - 0
    - 0
    limits:
    - - -.inf
      - .inf
    - - -.inf
      - .inf
    stiffness: 0
    springref: 0
    damping: 0
    extras: {}
  - name: joint_14
    initial:
    - 0
    - 0
    limits:
    - - -.inf
      - .inf
    - - -.inf
      - .inf
    stiffness: 0
    springref: 0
    damping: 0
    extras: {}
  self_collisions: []
control:
  sensors:
    links: &id001
    - link_0
    - link_1
    - link_2
    - link_3
    - link_4
    - link_5
    - link_6
    - link_7
    - link_8
    - link_9
    - link_10
    - link_11
    - link_12
    - link_13
    - link_14
    - link_15
    joints:
    - joint_0
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
    - joint_7
    - joint_8
    - joint_9
    - joint_10
    - joint_11
    - joint_12
    - joint_13
    - joint_14
    contacts: []
    xfrc: *id001
    muscles: []
    adhesions: []
    visuals: []
  motors:
  - joint_name: joint_0
    control_types:
    - position
    limits_torque:
    - -.inf
    - .inf
    gains: &id002
    - 0.001
    - 2.0e-05
    - 0
  - joint_name: joint_1
    control_types:
    - position
    limits_torque:
    - -.inf
    - .inf
    gains: *id002
  - joint_name: joint_2
    control_types:
    - position
    limits_torque:
    - -.inf
    - .inf
    gains: *id002
  - joint_name: joint_3
    control_types:
    - position
    limits_torque:
    - -.inf
    - .inf
    gains: *id002
  - joint_name: joint_4
    control_types:
    - position
    limits_torque:
    - -.inf
    - .inf
    gains: *id002
  - joint_name: joint_5
    control_types:
    - position
    limits_torque:
    - -.inf
    - .inf
    gains: *id002
  - joint_name: joint_6
    control_types:
    - position
    limits_torque:
    - -.inf
    - .inf
    gains: *id002
  - joint_name: joint_7
    control_types:
    - position
    limits_torque:
    - -.inf
    - .inf
    gains: *id002
  - joint_name: joint_8
    control_types:
    - position
    limits_torque:
    - -.inf
    - .inf
    gains: *id002
  - joint_name: joint_9
    control_types:
    - position
    limits_torque:
    - -.inf
    - .inf
    gains: *id002
  - joint_name: joint_10
    control_types:
    - position
    limits_torque:
    - -.inf
    - .inf
    gains: *id002
  - joint_name: joint_11
    control_types:
    - position
    limits_torque:
    - -.inf
    - .inf
    gains: *id002
  - joint_name: joint_12
    control_types:
    - position
    limits_torque:
    - -.inf
    - .inf
    gains: *id002
  - joint_name: joint_13
    control_types:
    - position
    limits_torque:
    - -.inf
    - .inf
    gains: *id002
  - joint_name: joint_14
    control_types:
    - position
    limits_torque:
    - -.inf
    - .inf
    gains: *id002
extensions:
- loader: lilytorch.farms_examples.zebrafishsim.pd_controller.PositionController
  config:
    freq: 10.0
    twl: 20
    amp: 140
