
# 2D flow past cylinder, Re = 200  (2*R*U/nu = 2*0.1*0.1/1e-4 = 200)
# Uses the FFT Poisson solver

solver:
  use_gpu           : True
  nthreads          : 16
  Nx                : 512
  Ny                : 256
  xmin              : -0.5
  xmax              :  1.5
  ymin              : -0.5
  ymax              :  0.5
  nt                : 100000
  nu                : 1.0e-4
  rho               : 1.0
  dt                : 0.001
  convection_method : "quick"
  poisson_method    : "fft"

  poisson_tol            : 1.0e-4
  jacobi_weight          : 0.7
  poisson_max_mgcg_cycles: 3
  poisson_max_cycles     : 30
  poisson_nsmoothing     : 5
  poisson_verbose        : False
  poisson_folder         : "lilytorch/data/"

boundary_conditions:
  BC_type_u:
  - "D"
  - "D"
  - "N"
  - "N"
  BC_values_u:
  - 0.1
  - 0.1
  - 0.0
  - 0.0
  BC_type_v:
  - "N"
  - "N"
  - "D"
  - "D"
  BC_values_v:
  - 0.0
  - 0.0
  - 0.0
  - 0.0

body:
  type: composite_analytical
  plotting: False
  sdf:
  - "lambda x, y: circle(x,y,xt=0,yt=0,r=0.1)"
  update_maps:
  - rotation: "lambda t: 0*t"
    translation:
      - "lambda t: 0*t"
      - "lambda t: 0*t"

output:
  save_path   : "/data/andreaferrario/ns_data/cylinder_2d_Re200_fft/"
  save_frames : True
  save_every  : 500
  vmin        : "auto"
  vmax        : "auto"
  save_uv     : False
