sdf: ../models/sphere/sphere.sdf
spawn:
  loader: 0
  mode: !!python/object/apply:farms_core.model.options.SpawnMode
  - free
  pose:
  - -0.17
  - -0.17
  - 0.22
  - 1
  - 1
  - 3.141592653589793
  velocity:
  - -1
  - 1
  - -1
  - 10
  - 10
  - 10
  extras: {}
morphology:
  links:
  - name: base_link
    collisions: true
    friction:
    - 0.5
    - 0
    - 0
    extras:
      restitution: 0.5
      linearDamping: 0
      angularDamping: 0
    fluid_interaction: true
    density: 900.0
    drag_coefficients:
    - - -1.0
      - -1.0
      - -1.0
    - - -0.001
      - -0.001
      - -0.001
  self_collisions: []
  joints: []
control:
  sensors:
    links:
    - base_link
    joints: []
    contacts: []
    xfrc:
    - base_link
    muscles: []
    adhesions: []
    visuals: []
  motors: []
  hill_muscles: []
extensions:
- loader: farms_core.model.control.AnimatController
  config: {}
- loader: farms_mujoco.swimming.extension.SwimmingExtension
  config:
    water_properties: null
