"""TaskExtension that replaces the compiled MuJoCo skybox with a solid colour.

The FARMS default sky is a blue-to-black gradient with random white stars,
generated by ``night_sky()`` in farms_mujoco.

Why tex_data alone is not enough
---------------------------------
In MuJoCo 3.x ``mjr_makeContext`` (called when a ``mujoco.Renderer`` is
created) regenerates built-in textures *directly on the GPU* without writing
back to ``model.tex_data``.  Zeroing ``tex_data`` before the Renderer is
created therefore has no effect on the rendered image.

Fix
---
``SkyModifier.__init__`` (called by the FARMS extension loader *before* any
``mujoco.Renderer`` is ever constructed) monkey-patches
``mujoco.Renderer.__init__`` so that, after the parent ``__init__`` returns,
the skybox texture is immediately re-uploaded with the desired colour.  This
is ordering-independent: it fires for every renderer, including the live
viewer and CameraRecording renderers, regardless of when they are created.

``end_episode`` restores the original ``__init__``.
"""

import mujoco
import numpy as np
from farms_core.simulation.extensions import TaskExtension


class SkyModifier(TaskExtension):
    """Replace the MuJoCo skybox texture with a solid colour.

    Parameters
    ----------
    rgb : list[float]
        Target sky colour as ``[r, g, b]`` in [0, 1].  Defaults to black.
    """

    def __init__(self, *, rgb=None):
        super().__init__()
        self.rgb = list(rgb) if rgb is not None else [0.0, 0.0, 0.0]
        self._orig_renderer_init = mujoco.Renderer.__init__
        self._install_renderer_patch()

    @classmethod
    def from_options(cls, config, experiment_options):
        del experiment_options
        return cls(rgb=config.get('rgb', [0.0, 0.0, 0.0]))

    # ------------------------------------------------------------------
    def _find_skybox_id(self, ptr):
        """Return the compiled texture index of the skybox, or -1."""
        # 1. Try by name.
        try:
            tid = mujoco.mj_name2id(ptr, mujoco.mjtObj.mjOBJ_TEXTURE, 'skybox')
            if tid >= 0:
                return tid
        except Exception:
            pass

        # 2. Scan by texture type (mjTEXTURE_SKYBOX = 2).
        try:
            skybox_type = int(mujoco.mjtTexture.mjTEXTURE_SKYBOX)
            for i in range(int(ptr.ntex)):
                if int(ptr.tex_type[i]) == skybox_type:
                    return i
        except Exception:
            pass

        return -1

    def _apply_to_renderer(self, renderer, model):
        """Zero skybox pixels in tex_data and upload to this renderer's GPU context."""
        ptr = getattr(model, 'ptr', model)
        tex_id = self._find_skybox_id(ptr)
        if tex_id < 0:
            return

        adr = int(ptr.tex_adr[tex_id])
        h   = int(ptr.tex_height[tex_id])
        w   = int(ptr.tex_width[tex_id])
        tex_arr = ptr.tex_data if hasattr(ptr, 'tex_data') else ptr.tex_rgb
        bpp = int(ptr.tex_nchannel[tex_id]) if hasattr(ptr, 'tex_nchannel') else 3

        n = h * w * bpp
        pixel = np.array([int(c * 255) for c in self.rgb], dtype=np.uint8)
        if bpp == 4:
            pixel = np.append(pixel, np.uint8(255))
        tex_arr[adr:adr + n] = np.tile(pixel, h * w)

        ctx = getattr(renderer, '_mjr_context', None)
        if ctx is not None:
            mujoco.mjr_uploadTexture(ptr, ctx, tex_id)

    # ------------------------------------------------------------------
    def _install_renderer_patch(self):
        """Monkey-patch mujoco.Renderer.__init__ to auto-upload the sky colour."""
        orig = self._orig_renderer_init
        sky_modifier = self  # closed over

        def _patched_init(renderer_self, model, *args, **kwargs):
            orig(renderer_self, model, *args, **kwargs)
            # Re-make the GL context current (mjr_makeContext may have released it)
            gl_ctx = getattr(renderer_self, '_gl_context', None)
            if gl_ctx is not None:
                gl_ctx.make_current()
            sky_modifier._apply_to_renderer(renderer_self, model)

        mujoco.Renderer.__init__ = _patched_init

    # ------------------------------------------------------------------
    def initialize_episode(self, task, physics):
        """Belt-and-suspenders: also upload to renderers already created."""
        ptr = getattr(physics.model, 'ptr', physics.model)
        for ext in task.extensions:
            renderer = getattr(ext, 'renderer', None)
            if renderer is not None:
                self._apply_to_renderer(renderer, ptr)

    # ------------------------------------------------------------------
    def end_episode(self, task, physics):
        """Restore the original mujoco.Renderer.__init__."""
        del task, physics
        mujoco.Renderer.__init__ = self._orig_renderer_init

